name: CI/CD Flow

on:
  push:
    branches: [ "upd" ]
  pull_request:
    branches: [ "upd" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate module jars
        run: gradle clean build -x test
      - name: login Docker hub
        uses: docker/login-action@v2
        with:
          username: e1cringe
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker tea-app
        run: docker build --file ./docker/Dockerfile --tag e1cringe/tea-app:latest .
      - name: Push Docker tea-app
        run: docker push e1cringe/tea-app


