name: CI/CD Flow

on:
  push:
    branches: [ "upd" ]
  pull_request:
    branches: [ "upd" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
           java-version: '17'
           distribution: 'temurin'
           cache: gradle
      -  name: Generate module jars
         run: gradle clean build -x test
      -  name: Build & Push Docker tea-app
         uses: mr-smithers-excellent/docker-build-push@v5
         with:
           context: ./tea_app_test
           image: e1cringe/tea-app
           tags: latest
           registry: docker.io
           dockerfile: ./tea_app_test
           username: e1cringe
           password: ${{ secrets.DOCKER_PASSWORD }}

